export const CHAT_STATES = {
  IDLE: "idle",
  RUNNING: "running",
  WAITING_CONFIRM: "waiting_confirm",
  WAITING_PHASE_B_FEEDBACK: "waiting_phase_b_feedback",
  ERROR: "error",
  INTAKE: "intake",
  DRAFTING: "drafting",
  PENDING_CONFIRMATION: "pending_confirmation",
  CONFIRMED_CONTENT: "confirmed_content",
  REVIEWING: "reviewing",
  LAYOUT_SOLVING: "layout_solving",
  READY_TO_EXPORT: "ready_to_export",
  EXPORTED: "exported",
  BLOCKED: "blocked"
} as const;

export const CONTROLLER_EVENTS = {
  USER_PROVIDED_INFO: "USER_PROVIDED_INFO",
  PARSE_COMPLETED: "PARSE_COMPLETED",
  PATCH_GENERATED: "PATCH_GENERATED",
  PATCH_ACCEPTED: "PATCH_ACCEPTED",
  PATCH_REJECTED: "PATCH_REJECTED",
  REVIEW_FAILED: "REVIEW_FAILED",
  LAYOUT_OVERFLOW: "LAYOUT_OVERFLOW",
  USER_APPROVED_MULTIPAGE: "USER_APPROVED_MULTIPAGE",
  EXPORT_REQUESTED: "EXPORT_REQUESTED"
} as const;

const TRANSITIONS = {
  [CHAT_STATES.INTAKE]: {
    [CONTROLLER_EVENTS.USER_PROVIDED_INFO]: CHAT_STATES.DRAFTING,
    [CONTROLLER_EVENTS.PARSE_COMPLETED]: CHAT_STATES.PENDING_CONFIRMATION
  },
  [CHAT_STATES.DRAFTING]: {
    [CONTROLLER_EVENTS.USER_PROVIDED_INFO]: CHAT_STATES.DRAFTING,
    [CONTROLLER_EVENTS.PATCH_GENERATED]: CHAT_STATES.PENDING_CONFIRMATION,
    [CONTROLLER_EVENTS.REVIEW_FAILED]: CHAT_STATES.BLOCKED
  },
  [CHAT_STATES.PENDING_CONFIRMATION]: {
    [CONTROLLER_EVENTS.PATCH_ACCEPTED]: CHAT_STATES.CONFIRMED_CONTENT,
    [CONTROLLER_EVENTS.PATCH_REJECTED]: CHAT_STATES.DRAFTING
  },
  [CHAT_STATES.CONFIRMED_CONTENT]: {
    [CONTROLLER_EVENTS.REVIEW_FAILED]: CHAT_STATES.BLOCKED,
    [CONTROLLER_EVENTS.LAYOUT_OVERFLOW]: CHAT_STATES.LAYOUT_SOLVING,
    [CONTROLLER_EVENTS.EXPORT_REQUESTED]: CHAT_STATES.READY_TO_EXPORT
  },
  [CHAT_STATES.LAYOUT_SOLVING]: {
    [CONTROLLER_EVENTS.USER_APPROVED_MULTIPAGE]: CHAT_STATES.READY_TO_EXPORT,
    [CONTROLLER_EVENTS.REVIEW_FAILED]: CHAT_STATES.BLOCKED
  },
  [CHAT_STATES.READY_TO_EXPORT]: {
    [CONTROLLER_EVENTS.EXPORT_REQUESTED]: CHAT_STATES.EXPORTED
  }
} as const;

export function transitionWorkflowState(currentState, event) {
  const nextState = TRANSITIONS?.[currentState]?.[event];
  if (!nextState) {
    throw new Error(`BLOCKED: invalid controller transition (${String(currentState)} -> ${String(event)})`);
  }
  return nextState;
}
