export const TEMPLATE_LIST = [
  "classic",
  "modern",
  "minimal",
  "professional",
  "two-column",
  "creative",
  "ats",
  "academic",
  "elegant",
  "executive",
  "developer",
  "designer",
  "startup",
  "formal",
  "infographic",
  "compact",
  "euro",
  "clean",
  "bold",
  "timeline",
  "nordic",
  "corporate",
  "consultant",
  "finance",
  "medical",
  "gradient",
  "metro",
  "material",
  "coder",
  "blocks",
  "magazine",
  "artistic",
  "retro",
  "neon",
  "watercolor",
  "swiss",
  "japanese",
  "berlin",
  "luxe",
  "rose",
  "architect",
  "legal",
  "teacher",
  "scientist",
  "engineer",
  "sidebar",
  "card",
  "zigzag",
  "ribbon",
  "mosaic"
];

export const TEMPLATE_ALIASES = {
  magic: "modern",
  premium: "classic",
  "left-right": "two-column",
  compact: "compact",
  ats: "ats"
};

const LIGHT = {
  layout: "single",
  bg: "#ffffff",
  text: "#111111",
  accent: "#2563eb",
  muted: "#4b5563",
  sidebarBg: "#f8fafc",
  sidebarText: "#0f172a"
};

const DARK = {
  layout: "single",
  bg: "#111827",
  text: "#f9fafb",
  accent: "#22d3ee",
  muted: "#cbd5e1",
  sidebarBg: "#1f2937",
  sidebarText: "#e5e7eb"
};

const TWO_COLUMN_DARK = {
  layout: "two-column",
  bg: "#ffffff",
  text: "#111111",
  accent: "#2563eb",
  muted: "#4b5563",
  sidebarBg: "#1e3a8a",
  sidebarText: "#f8fafc"
};

const TWO_COLUMN_CODER = {
  layout: "two-column",
  bg: "#ffffff",
  text: "#111111",
  accent: "#0ea5e9",
  muted: "#4b5563",
  sidebarBg: "#0f172a",
  sidebarText: "#e2e8f0"
};

export const TEMPLATE_STYLES = {
  classic: { ...LIGHT, accent: "#1f2937" },
  modern: { ...LIGHT, accent: "#0ea5e9" },
  minimal: { ...LIGHT, accent: "#6b7280" },
  professional: { ...LIGHT, accent: "#334155" },
  "two-column": TWO_COLUMN_DARK,
  creative: { ...LIGHT, accent: "#c026d3" },
  ats: { ...LIGHT, accent: "#111827" },
  academic: { ...LIGHT, accent: "#4338ca" },
  elegant: { ...LIGHT, accent: "#1d4ed8" },
  executive: { ...LIGHT, accent: "#0f172a" },
  developer: { ...LIGHT, accent: "#0284c7" },
  designer: { ...LIGHT, accent: "#db2777" },
  startup: { ...LIGHT, accent: "#16a34a" },
  formal: { ...LIGHT, accent: "#1f2937" },
  infographic: { ...LIGHT, accent: "#7c3aed" },
  compact: { ...LIGHT, accent: "#111827" },
  euro: { ...LIGHT, accent: "#1d4ed8" },
  clean: { ...LIGHT, accent: "#64748b" },
  bold: { ...LIGHT, accent: "#dc2626" },
  timeline: { ...LIGHT, accent: "#2563eb" },
  nordic: { ...LIGHT, accent: "#0ea5e9" },
  corporate: { ...LIGHT, accent: "#1f2937" },
  consultant: { ...LIGHT, accent: "#334155" },
  finance: { ...LIGHT, accent: "#0f766e" },
  medical: { ...LIGHT, accent: "#059669" },
  gradient: { ...LIGHT, accent: "#7c3aed" },
  metro: { ...LIGHT, accent: "#0369a1" },
  material: { ...LIGHT, accent: "#2563eb" },
  coder: TWO_COLUMN_CODER,
  blocks: { ...LIGHT, accent: "#ea580c" },
  magazine: { ...LIGHT, accent: "#be123c" },
  artistic: { ...LIGHT, accent: "#9333ea" },
  retro: { ...LIGHT, accent: "#b45309" },
  neon: DARK,
  watercolor: { ...LIGHT, accent: "#0891b2" },
  swiss: { ...LIGHT, accent: "#dc2626" },
  japanese: { ...LIGHT, accent: "#991b1b" },
  berlin: { ...LIGHT, accent: "#111827" },
  luxe: { ...LIGHT, accent: "#7c2d12" },
  rose: { ...LIGHT, accent: "#e11d48" },
  architect: { ...LIGHT, accent: "#374151" },
  legal: { ...LIGHT, accent: "#1e3a8a" },
  teacher: { ...LIGHT, accent: "#16a34a" },
  scientist: { ...LIGHT, accent: "#0e7490" },
  engineer: { ...LIGHT, accent: "#0369a1" },
  sidebar: TWO_COLUMN_DARK,
  card: { ...LIGHT, accent: "#0284c7" },
  zigzag: { ...LIGHT, accent: "#d946ef" },
  ribbon: { ...LIGHT, accent: "#ef4444" },
  mosaic: { ...LIGHT, accent: "#0ea5e9" }
};

export const TEMPLATE_GROUPS = {
  "base-20": TEMPLATE_LIST.slice(0, 20),
  "batch-1-industry": TEMPLATE_LIST.slice(20, 25),
  "batch-2-modern-tech": TEMPLATE_LIST.slice(25, 30),
  "batch-3-creative": TEMPLATE_LIST.slice(30, 35),
  "batch-4-culture": TEMPLATE_LIST.slice(35, 40),
  "batch-5-specialized": TEMPLATE_LIST.slice(40, 45),
  "batch-6-layout": TEMPLATE_LIST.slice(45)
};
